# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ee783f63b1942afb49c826afc1af1279f4c5cc2fa6eef2764356113932d84874bdf5ed93c8a4ee7690f8b3e0511ce0f4f3ec341e96d88295b0492648ab43e0f

test:
  secret_key_base: b9da2921583804526756a46c3548110c0d64420228f26cad09b407ae044e0505fa0118b85cf996120c20614f629cb5f970d44ed01a02b2535e89a9b60ab1588a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
